### PR TITLE
Fix Unit Tests

### PR DESCRIPTION
**Pull request by JonathanZhu11**
Modify some R and Python failing tests.

- Fix the python buildandinstall to absolutely find the correct sqlmlutils link
- Fix some script issues, where we would put N'' around binary content in CREATE EXTERNAL LIBRARY which made the scripts not runnable.
- Use funcsigs and data packages for most python tests because they are much smaller so GCI should go faster.
- Add a cleanup helper at the end of all R tests so that we ensure we start with a clean slate on every test

### CODE REVIEW

**Comment by guitarnana** [comment]
why are we checking in binary under dist?

**Comment by guitarnana** [comment]
>- Fix some script issues

Can you please clarify what are the issues?

**Comment by JonathanZhu11** [comment]
> why are we checking in binary under dist?

We always do - it makes it easier for developers who want to try it out to enlist and just use the prebuilt binaries. I suppose now that we use Github releases it's not really necessary anymore.

**Review by guitarnana — APPROVED** [review]
:shipit:

**Pull request closed without merging**
