### PR TITLE
Update sqlPackage.R

### PR DESCRIPTION
**Pull request by SchnalzenbergerM**
sqlRemoteExecuteFun needs languageName to work

If R-Versions don't match, the code is not working (error in paste0 because languageName is not set)

### CODE REVIEW

**Comment by SchnalzenbergerM** [comment]
Hi the tests did not fail due to my changes but due to the missing connection to a Database ....  where is the database instance in the tests running

**Comment by guitarnana** [comment]
Thank you @SchnalzenbergerM for the fix. We will take a look at Travis CI pipeline and will address the issue. Please be patient with us.

**Review by ivannp — CHANGES_REQUESTED** [review]
Thanks for fixing this!

Could you remove the comment explaining the change?

**Comment by SchnalzenbergerM** [comment]
done removing the comment ....

**Review by ivannp — APPROVED** [review]

**Review by Aniruddh25 — APPROVED** [review]
:shipit:

**Pull request merged**
